[project]
name = "qualis-zotero"
<<<<<<< HEAD
version = "0.1.0"
=======
version = "0.1.1"
>>>>>>> 7ef9f66 (atualização 1)
description = "Integra Zotero, OpenAlex e Qualis CAPES"
authors = [{ name="Wilson Vanucci", email="wilsonvanuccicl@gmail.com" }]
license = {text = "MIT"}
readme = "README.md"
dependencies = [
    "pandas",
    "requests",
    "PyYAML",
    "tqdm",
    "thefuzz"
]

<<<<<<< HEAD
=======
[project.urls]
"Homepage" = "https://github.com/wvanucci/Qualis-Zotero"
"Documentation" = "https://qualis-zotero.readthedocs.io"

>>>>>>> 7ef9f66 (atualização 1)
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"